name: safespeak
description: SafeSpeak - Anonymous Harassment Evidence Collector
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    flutter_launcher_icons: ^0.13.1
  path_provider: ^2.0.11
  permission_handler: ^10.4.0
  encrypt: ^5.0.1
  crypto: ^3.0.2
  flutter_sound: ^9.2.13
  screenshot: ^1.3.0
  shared_preferences: ^2.1.1
  record: ^5.0.0
  path_provider: ^2.0.0



  
  path_provider: ^2.0.15
  flutter_sound: ^9.2.13
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/calculator.png"
flutter:
  uses-material-design: true



